export { createTransactionRepository } from '@/feature/transactions/repository.ts';
export type { TransactionRepository } from '@/feature/transactions/repository.ts';
export { createTransactionService } from '@/feature/transactions/service.ts';
export type { TransactionService, TransactionServiceDeps, ListForPeriodResult, ListInstallmentsResult } from '@/feature/transactions/service.ts';
export { createTransactionFormModal } from '@/feature/transactions/form-modal.ts';
export type { TransactionFormModalDeps, TransactionFormModalOptions, ImportRulesPort } from '@/feature/transactions/form-modal.ts';
export { createTransactionActions, isTransfer } from '@/feature/transactions/actions.ts';
export type { TransactionActions, TransactionActionsDeps, TxLike } from '@/feature/transactions/actions.ts';
export { createTransactionsApi } from '@/feature/transactions/api.ts';
export type { TransactionsApi } from '@/feature/transactions/api.ts';
export { createTransactionsPage, createTransactionsListPage } from '@/feature/transactions/page.ts';
export type { TransactionsPageDeps, TransactionsPageConfig } from '@/feature/transactions/page.ts';
export { createInstallmentsPage } from '@/feature/transactions/installments-page.ts';
