name: cdb-judas

services:
  backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.backend
      network: host
      args:
        APP_VERSION: "0.9.0"
    image: cdb-judas-backend:0.9.0
    container_name: cdb-judas-backend
    environment:
      STORAGE_JSON_PATH: /data
      APP_LOGLEVEL_ROOT: INFO
    ports: ["8080:8080"]
    volumes: [ ./data:/data ]
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.frontend
      args:
        APP_VERSION: "0.1.0"
    image: cdb-judas-frontend:0.1.0
    container_name: cdb-judas-frontend
    ports: ["8081:80"]
    depends_on: [backend]
    restart: unless-stopped
