/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cost-center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCenter"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SelfResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SelfResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna a versão do sistema extraída do pom.xml */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Balances */
        get: {
            parameters: {
                query?: {
                    period?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalanceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/closing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClosingResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Set */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClosingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClosingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Clear */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transaction/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRule"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRule"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transaction/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRule"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/accounts/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: {
            parameters: {
                query?: {
                    dateFrom?: components["schemas"]["LocalDate"];
                    dateTo?: components["schemas"]["LocalDate"];
                    limit?: number;
                    status?: string;
                    type?: string;
                };
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transactions/by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Category */
        get: {
            parameters: {
                query?: {
                    categoryIds?: string;
                };
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transactions/import/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatementConfirmRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transactions/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        password?: string;
                        accountId?: components["schemas"]["UUID"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/{accId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List By Account */
        get: {
            parameters: {
                query?: {
                    dateFrom?: components["schemas"]["LocalDate"];
                    dateTo?: components["schemas"]["LocalDate"];
                    limit?: number;
                    status?: string;
                    type?: string;
                };
                header?: never;
                path: {
                    accId: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accId: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/{accId}/transactions/{txId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: {
                    mode?: string;
                };
                header?: never;
                path: {
                    txId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accId: components["schemas"]["UUID"];
                    txId: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/accounts/{accId}/transactions/{txId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    txId: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/accounts/{accountId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/accounts/{accountId}/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: {
                    strategy?: string;
                    targetId?: components["schemas"]["UUID"];
                };
                header?: never;
                path: {
                    accountId: components["schemas"]["UUID"];
                    cardId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update Status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: components["schemas"]["UUID"];
                    cardId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: {
                    strategy?: string;
                    targetId?: components["schemas"]["UUID"];
                };
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance */
        get: {
            parameters: {
                query?: {
                    period?: string;
                    year?: number;
                };
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/categories/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfer Category */
        get: {
            parameters: {
                query?: {
                    nature?: string;
                };
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransferCategoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: {
                    strategy?: string;
                    targetId?: components["schemas"]["UUID"];
                };
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/{uuid}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monthly Result */
        get: {
            parameters: {
                query?: {
                    month?: number;
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tag"][];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tag"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{uuid}/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: {
                    strategy?: string;
                    targetId?: components["schemas"]["UUID"];
                };
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                    uuid: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tag"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountRequest: {
            name: string;
            type: string;
            color: string;
            active?: boolean;
            creditLimit?: number;
            overdraftLimit?: number;
            /** Format: int32 */
            closingDay?: number;
            /** Format: int32 */
            dueDay?: number;
        };
        AccountResponse: {
            id?: components["schemas"]["UUID"];
            name?: string;
            type?: string;
            color?: string;
            active?: boolean;
            creditLimit?: number;
            overdraftLimit?: number;
            /** Format: int32 */
            closingDay?: number;
            /** Format: int32 */
            dueDay?: number;
            currentBalance?: number;
            cards?: components["schemas"]["Card"][];
        };
        BalanceResponse: {
            accountId?: components["schemas"]["UUID"];
            period?: components["schemas"]["YearMonth"];
            balance?: number;
        };
        Card: {
            id?: components["schemas"]["UUID"];
            last4?: string;
            accountId?: components["schemas"]["UUID"];
            active?: boolean;
        };
        CardRequest: {
            last4: string;
        };
        CardResponse: {
            id?: components["schemas"]["UUID"];
            last4?: string;
            accountId?: components["schemas"]["UUID"];
            active?: boolean;
        };
        CardStatusRequest: {
            active?: boolean;
        };
        CategoryResponse: {
            id?: components["schemas"]["UUID"];
            name?: string;
            nature?: string;
            parentId?: components["schemas"]["UUID"];
            isSystem?: boolean;
            active?: boolean;
        };
        ClosingRequest: {
            period: string;
        };
        ClosingResponse: {
            period?: string;
        };
        CostCenter: {
            id?: components["schemas"]["UUID"];
            description?: string;
        };
        CreateRequest: {
            name: string;
            nature: string;
            parentId?: components["schemas"]["UUID"];
        };
        HistoricalResult: {
            month?: string;
            /** Format: double */
            incomes?: number;
            /** Format: double */
            expenses?: number;
        };
        ImportRule: {
            id?: components["schemas"]["UUID"];
            personId?: components["schemas"]["UUID"];
            name?: string;
            triggers?: string[];
            accountId?: components["schemas"]["UUID"];
            categoryId?: components["schemas"]["UUID"];
            planned?: boolean;
            createdAt?: components["schemas"]["LocalDateTime"];
        };
        ImportRuleRequest: {
            name: string;
            triggers: string[];
            accountId?: components["schemas"]["UUID"];
            categoryId?: components["schemas"]["UUID"];
            planned?: boolean;
        };
        /**
         * Format: date
         * @example 2022-03-10
         */
        LocalDate: string;
        /**
         * Format: date-time
         * @example 2022-03-10T12:15:50
         */
        LocalDateTime: string;
        LoginRequest: {
            username?: string;
            password?: string;
        };
        MonthlyResult: {
            /** Format: double */
            incomes?: number;
            /** Format: double */
            expenses?: number;
            /** Format: double */
            result?: number;
            history?: components["schemas"]["HistoricalResult"][];
        };
        PatchStatusRequest: {
            status: components["schemas"]["Status"];
            paymentDate: components["schemas"]["LocalDate"];
        };
        Preferences: {
            theme?: string;
            language?: string;
            locale?: string;
            sidebarCollapsed?: boolean;
        };
        PreferencesRequest: {
            theme?: string;
            language?: string;
            locale?: string;
            sidebarCollapsed?: boolean;
        };
        Row: {
            description: string;
            amount: number;
            date: components["schemas"]["LocalDate"];
            originalDate?: components["schemas"]["LocalDate"];
            /** Format: int32 */
            installmentNumber?: number;
            /** Format: int32 */
            installmentTotal?: number;
            transactionType?: components["schemas"]["Type"];
            categoryId: components["schemas"]["UUID"];
            planned?: boolean;
            cardId?: components["schemas"]["UUID"];
            tagIds?: string[];
        };
        SelfResponse: {
            id?: string;
            username?: string;
            name?: string;
            preferences?: components["schemas"]["Preferences"];
        };
        StatementConfirmRequest: {
            type: components["schemas"]["StatementType"];
            accountId?: components["schemas"]["UUID"];
            rows: components["schemas"]["Row"][];
        };
        /** @enum {string} */
        StatementType: "CREDIT_CARD_INVOICE" | "BANK_STATEMENT";
        /** @enum {string} */
        Status: "SCHEDULED" | "CONFIRMED" | "PENDING";
        Tag: {
            id?: components["schemas"]["UUID"];
            personId?: components["schemas"]["UUID"];
            name?: string;
            color?: string;
            createdAt?: components["schemas"]["LocalDateTime"];
        };
        TagRequest: {
            name: string;
            color: string;
        };
        TransactionRequest: {
            description: string;
            amount: number;
            date: components["schemas"]["LocalDate"];
            categoryId: components["schemas"]["UUID"];
            accountId?: components["schemas"]["UUID"];
            planned?: boolean;
            status: components["schemas"]["Status"];
            type: components["schemas"]["Type"];
            /** Format: int32 */
            installments?: number;
            editMode?: string;
            deleteMode?: string;
            notes?: string;
            cardId?: components["schemas"]["UUID"];
            tagIds?: string[];
        };
        TransactionResponse: {
            id?: components["schemas"]["UUID"];
            description?: string;
            amount?: number;
            date?: components["schemas"]["LocalDate"];
            categoryId?: components["schemas"]["UUID"];
            accountId?: components["schemas"]["UUID"];
            status?: components["schemas"]["Status"];
            type?: components["schemas"]["Type"];
            planned?: boolean;
            paymentDate?: components["schemas"]["LocalDate"];
            groupId?: components["schemas"]["UUID"];
            /** Format: int32 */
            installmentNumber?: number;
            /** Format: int32 */
            totalInstallments?: number;
            notes?: string;
            cardId?: components["schemas"]["UUID"];
            tagIds?: string[];
        };
        TransferCategoryResponse: {
            id?: components["schemas"]["UUID"];
        };
        TransferRequest: {
            fromAccountId: components["schemas"]["UUID"];
            toAccountId: components["schemas"]["UUID"];
            date: components["schemas"]["LocalDate"];
            amount: number;
        };
        /** @enum {string} */
        Type: "EXPENSE" | "INCOME";
        /** Format: uuid */
        UUID: string;
        UpdateMeRequest: {
            name?: string;
            preferences?: components["schemas"]["PreferencesRequest"];
        };
        UpdateRequest: {
            name: string;
            parentId?: components["schemas"]["UUID"];
            active?: boolean;
        };
        YearMonth: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            /** Format: int64 */
            prolepticMonth?: number;
            /** Format: int32 */
            monthValue?: number;
            leapYear?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
