package br.commons.framework.persistence.jdbc.primitives;

import org.jspecify.annotations.NullMarked;

import java.sql.Connection;
import java.sql.JDBCType;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * Decodifica as constantes inteiras da API JDBC para o seu nome simbólico.
 *
 * <p>Cada família de constantes tem o seu próprio método porque os valores colidem entre famílias
 * (ex.: {@code HOLD_CURSORS_OVER_COMMIT == TRANSACTION_READ_UNCOMMITTED == RETURN_GENERATED_KEYS == 1}),
 * logo um decodificador único seria ambíguo. Usado sobretudo em logs de {@code trace} para tornar
 * legível o argumento numérico cru.
 */
@NullMarked
public abstract class JDBCConstants {
    private JDBCConstants(){}

    /** Nível de isolamento — {@link Connection#TRANSACTION_NONE} e afins. */
    public static String transactionIsolation(int level) {
        return switch (level) {
            case Connection.TRANSACTION_NONE -> "TRANSACTION_NONE";
            case Connection.TRANSACTION_READ_UNCOMMITTED -> "TRANSACTION_READ_UNCOMMITTED";
            case Connection.TRANSACTION_READ_COMMITTED -> "TRANSACTION_READ_COMMITTED";
            case Connection.TRANSACTION_REPEATABLE_READ -> "TRANSACTION_REPEATABLE_READ";
            case Connection.TRANSACTION_SERIALIZABLE -> "TRANSACTION_SERIALIZABLE";
            default -> unknown(level);
        };
    }

    /** Tipo do {@code ResultSet} — {@link ResultSet#TYPE_FORWARD_ONLY} e afins. */
    public static String resultSetType(int type) {
        return switch (type) {
            case ResultSet.TYPE_FORWARD_ONLY -> "TYPE_FORWARD_ONLY";
            case ResultSet.TYPE_SCROLL_INSENSITIVE -> "TYPE_SCROLL_INSENSITIVE";
            case ResultSet.TYPE_SCROLL_SENSITIVE -> "TYPE_SCROLL_SENSITIVE";
            default -> unknown(type);
        };
    }

    /** Concorrência do {@code ResultSet} — {@link ResultSet#CONCUR_READ_ONLY} e afins. */
    public static String concurrency(int concurrency) {
        return switch (concurrency) {
            case ResultSet.CONCUR_READ_ONLY -> "CONCUR_READ_ONLY";
            case ResultSet.CONCUR_UPDATABLE -> "CONCUR_UPDATABLE";
            default -> unknown(concurrency);
        };
    }

    /** Holdability do cursor — {@link ResultSet#HOLD_CURSORS_OVER_COMMIT} e afins. */
    public static String holdability(int holdability) {
        return switch (holdability) {
            case ResultSet.HOLD_CURSORS_OVER_COMMIT -> "HOLD_CURSORS_OVER_COMMIT";
            case ResultSet.CLOSE_CURSORS_AT_COMMIT -> "CLOSE_CURSORS_AT_COMMIT";
            default -> unknown(holdability);
        };
    }

    /** Direção do fetch — {@link ResultSet#FETCH_FORWARD} e afins. */
    public static String fetchDirection(int direction) {
        return switch (direction) {
            case ResultSet.FETCH_FORWARD -> "FETCH_FORWARD";
            case ResultSet.FETCH_REVERSE -> "FETCH_REVERSE";
            case ResultSet.FETCH_UNKNOWN -> "FETCH_UNKNOWN";
            default -> unknown(direction);
        };
    }

    /** Chaves geradas — {@link Statement#RETURN_GENERATED_KEYS} e afins. */
    public static String generatedKeys(int autoGeneratedKeys) {
        return switch (autoGeneratedKeys) {
            case Statement.RETURN_GENERATED_KEYS -> "RETURN_GENERATED_KEYS";
            case Statement.NO_GENERATED_KEYS -> "NO_GENERATED_KEYS";
            default -> unknown(autoGeneratedKeys);
        };
    }

    /** Tipo SQL de {@link java.sql.Types} pelo nome do {@link JDBCType} (ex.: {@code VARCHAR}). */
    public static String sqlType(int type) {
        try { return JDBCType.valueOf(type).getName(); }
        catch (IllegalArgumentException ex) { return unknown(type); }
    }

    private static String unknown(int value) { return "UNKNOWN(" + value + ")"; }
}
