erDiagram

%% CHECKING, SAVINGS
    MON_ACCOUNT_TYPE {
        CHAR(36) ID PK
        NUMERIC(1) FLG_ACTIVE
        VARCHAR(50) TXT_DESCRIPTION
    }

    MON_ACCOUNT {
        CHAR(36) ID PK
        VARCHAR(255) TXT_NAME
        CHAR(36) TXT_TYPE FK
        NUMERIC(1) FLG_ACTIVE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

    MON_ACCOUNT_TYPE ||--o{ MON_ACCOUNT : ""

%% SCHEDULED, CONFIRMED, PENDING
    MON_STATUS {
        VARCHAR(20) ID PK
        NUMERIC(1) FLG_ACTIVE
        VARCHAR(50) TXT_DESCRIPTION
    }

%% FIXED, VARIABLE
    MON_COST_CENTER {
        CHAR(36) ID PK
        NUMERIC(1) FLG_ACTIVE
        VARCHAR(50) TXT_DESCRIPTION
    }

    MON_TRANSACTION {
        CHAR(36) ID PK
        VARCHAR(255) TXT_DESCRIPTION
        NUMERIC(1) NUM_SIGNAL
        DECIMAL DEC_AMOUNT
        TIMESTAMP TMS_PURCHASE
        CHAR(36) COD_ACCOUNT FK
        CHAR(36) COD_COST_CENTER FK
        CHAR(36) COD_STATUS FK
        DATE DAT_PAYMENT
        CHAR(36) GROUP_ID
        INT NUM_INSTALLMENT
        INT NUM_INSTALLMENT_TOTAL
        VARCHAR(1000) TXT_NOTES
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

    MON_COST_CENTER ||--o{ MON_TRANSACTION : ""
    MON_STATUS ||--o{ MON_TRANSACTION : ""
    MON_ACCOUNT ||--o{ MON_TRANSACTION : ""
