erDiagram

    PEP_PERSON {
        CHAR(36) ID PK
        VARCHAR(255) TXT_NAME
        VARCHAR(20) TXT_LOCALE
        VARCHAR(20) TXT_LANGUAGE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMSUPDATED_AT
    }