 erDiagram

    USER {
        CHAR(36) ID PK
        CHAR(36) COD_PERSON FK
        VARCHAR(120) TXT_USERNAME
        CHAR(1) FLG_ACTIVE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

%% Last 5 user's password
    USER_CREDENTIAL {
        CHAR(36) ID PK
        CHAR(36) COD_USER PK
        VARCHAR(20) TXT_PASSWORD
        TIMESTAMP TMS_CREATE_AT
    }

    USER ||--|{ USER_CREDENTIAL : ""

    USER_PREFERENCES {
        CHAR(36) COD_USER PK, FK
        VARCHAR(20) TXT_PREFERENCE
        VARCHAR(60) TXT_VALUE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }
    USER ||--o{ USER_PREFERENCES : ""

    USER_ACCOUNT {
        CHAR(36) COD_USER PK
        CHAR(36) COD_ACCOUNT PK
        VARCHAR(20) TXT_COLOR
    }

    USER ||--o{ USER_ACCOUNT : ""

    USER_ACCOUNT_BALANCE {
        CHAR(36) COD_USER PK, FK
        CHAR(36) COD_ACCOUNT PK, FK
        NUMERIC(6) NUM_PERIOD PK
        DECIMAL DEC_BALANCE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

    USER_ACCOUNT ||--o{ USER_ACCOUNT_BALANCE : ""

    USER_TAG {
        CHAR(36) ID PK
        CHAR(36) COD_USER PK
        VARCHAR(20) TXT_COLOR
        VARCHAR(20) TXT_DESCRIPTION
        CHAR(1) FLG_ACTIVE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }
    USER ||--o{ USER_TAG : ""

%% EXPENSE, INCOME
    TRANSACTION_NATURE {
        CHAR(36) ID PK
        VARCHAR(10) TXT_DESCRIPTION
    }

    USER_CATEGORY {
        CHAR(36) ID PK
        CHAR(36) COD_PARENT FK
        CHAR(36) COD_NATURE FK
        VARCHAR(80) TXT_NAME
        CHAR(1) FLG_SYSTEM
        CHAR(1) FLG_ACTIVE
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

    USER ||--o{ USER_CATEGORY : ""
    TRANSACTION_NATURE ||--o{ USER_CATEGORY : ""

    USER_TRANSACTION {
        CHAR(36) COD_USER PK, FK
        CHAR(36) COD_ACCOUNT PK, FK
        CHAR(36) COD_TRANSACTION PK, FK
        CHAR(36) COD_CATEGORY FK
        TIMESTAMP TMS_CREATE_AT
        TIMESTAMP TMS_UPDATED_AT
    }

     USER_ACCOUNT ||--o{ USER_TRANSACTION: ""
     USER_TRANSACTION ||--o{ USER_CATEGORY : ""

    USER_TRANSACTION_TAG {
        CHAR(36) COD_TRANSACTION PK, FK
        CHAR(36) COD_TAG PK, FK
    }
    USER_TAG ||--o{ USER_TRANSACTION_TAG : ""
    USER_TRANSACTION ||--o{ USER_TRANSACTION_TAG : ""